name: Validate & Lint Migration

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
