name: check pagination

on:
 push:
 workflow_dispatch:

jobs:
   repo-list:
    runs-on: ubuntu-latest
    steps:
      - name: get user-id
        id: userdetails
        run: |
          user_id=$(curl -s https://api.github.com/users/Sakthi770 | jq '.id')
          echo "userid=$user_id" >> "$GITHUB_OUTPUT"
          echo $user_id
      - name: List Repositories
        id: repository
        run: |
          per_page=2
          page=1
          while [ "$page" != "null" ]; do
            response=$(curl -L -s -D - \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/search/repositories?q=user:Sakthi770?per_page=$per_page&page=$page")
            
            echo "$response" | grep -i "Link:" | grep -oP '(?<=<)[^>]+(?=>; rel="next")' | read next_page
            
            if [ -z "$next_page" ]; then
              page="null"
            else
              page=$(echo "$next_page" | grep -oP '(?<=page=)\d+')
            fi
            
            echo "$response" | jq '.'
          done
          
          response=$(curl -L \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{secrets.PAT_TOKEN}}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/search/repositories?q=user:Sakthi770&per_page=2")
          Repolist=$(echo "$response" | jq -r '.items[] | .full_name')
          echo " Repolist: $Repolist"
