name: foldersample
on:
  push:
jobs:     
 get-docker-image:
    runs-on: ubuntu-latest 
    steps:
      - name: Create cache for docker image
        uses: actions/cache@v4
        with:
          path: images
          key: image-key

      - name: Download docker image from source
        run: |
          mkdir -p images
          cd images
          touch dist.txt

 user-docker-image:
    runs-on: ubuntu-latest 
    needs:
      - get-docker-image
    steps:
      - name: Restore cached docker image
        uses: actions/cache/restore@v4
        with:
          path: images
          key: image-key

      - name: Use the image
        working-directory: images
        run: |
          ls
