name: test github command

on:
  push:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository owner login
        run: |
          echo ${{ github.event.repository.owner.login }}
          echo ${{ github.event.repository.owner }}
          echo ${{ github.repository_owner }}

      - name: Print
        run: env | sort
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
